baseURL = "http://snaphugo.org/"
languageCode = "en-us"
title = "Hugo Snap Demo"
theme = "hugo_theme_solit"

[params]
    footerText = "© 2019"
    googlefonts = "https://fonts.googleapis.com/css?family=Raleway:100"