name: demo-hugo-site
version: 0.1
summary: Demo Hugo Site - Snap a hugo site
description: |
 Build a hugo site and snap it with a webserver.

grade: stable
confinement: strict

parts:
  webserver:
    source: https://github.com/ryanjyoder/static-webserver.git
    source-type: git
    plugin: go
    go-importpath: github.com/ryanjyoder/static-webserver

  hugo:
    source: https://github.com/gohugoio/hugo.git
    source-type: git
    plugin: go
    go-importpath: github.com/gohugoio/hugo

  assets:
    source: public/
    organize:
      '*': public/
    plugin: dump

apps:
  webserver:
    command: static-webserver -port 8585 -dir $SNAP/public
    daemon: simple
    plugs: [network, network-bind]

  hugo:
    command: hugo
    plugs: [network, network-bind]
