name: demo-hugo-site
version: 0.1
summary: Demo Hugo Site - Snap a hugo site
description: |
 Build a hugo site and snap it with a webserver.

grade: stable
confinement: strict
environment:
    GO111MODULE: 'on'

parts:
  content:
    plugin: dump
    stage: [public]
    after: [hugo]

  hugo:
    plugin: nil
    build-packages: [curl]
    override-build: |
      echo "\nStarting override-build:"
      url=""
      arch=`echo $SNAPCRAFT_ARCH_TRIPLET | awk -F- '{print $1}'` 
      case "$arch" in
      x86_64) 
      url=https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_0.48_Linux-64bit.tar.gz
      ;;
      arm)
      url=https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_0.48_Linux-ARM.tar.gz
      ;;
      aarch64)
      url=https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_0.48_Linux-ARM64.tar.gz
      ;;
      i386)
      url=https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_0.48_Linux-32bit.tar.gz
      ;;
      *)
      echo SNAP_ARCH unknow type $SNAP_ARCH
      env
      exit 1
      esac
      curl $url -L --output hugo.tar.gz
      tar -xvzf hugo.tar.gz
      hugo


apps:
  hugo:
    command: webserver -dir $SNAP/public -port 1313 
    daemon: simple
    plugs: [network, network-bind]

