name: demo-hugo-site
version: 0.1
summary: Demo Hugo Site - Snap a hugo site
description: |
 Build a hugo site and snap it with a webserver.

grade: stable
confinement: strict
environment:
    GO111MODULE: 'on'

parts:
  content:
    plugin: dump
    stage: [config.toml,archetypes, content, data, layouts, static, themes]

parts:
  hugo:
    source: https://github.com/gohugoio/hugo.git
    source-tag: stable
    source-type: git
    plugin: go
    go-importpath: github.com/gohugoio/hugo
    build-packages:
      - git
    override-build: |
      echo "\nStarting override-build:"
      export GOPATH=$(dirname $SNAPCRAFT_PART_INSTALL)/go
      export PATH=$GOPATH/bin:$PATH
      cd $GOPATH/src/github.com/gohugoio/hugo
      echo ' * Running "go get -v github.com/magefile/mage"...'
      go get -v github.com/magefile/mage
      echo ' * Running "mage -v test"...'
      mage -v test
      echo " * Building hugo (build tag: none)..."
      [ "$SNAPCRAFT_PROJECT_GRADE" = "stable" ] && mage -v hugoNoGitInfo || mage -v hugo
      ./hugo version
      ldd hugo || :
      echo " * Building shell completion..."
      ./hugo gen autocomplete --completionfile=hugo-completion
      echo " * Installing to ${SNAPCRAFT_PART_INSTALL}..."
      install -d $SNAPCRAFT_PART_INSTALL/bin
      cp -av hugo $SNAPCRAFT_PART_INSTALL/bin/
      mv -v hugo-completion $SNAPCRAFT_PART_INSTALL/
      echo " * Stripping binary..."
      ls -l $SNAPCRAFT_PART_INSTALL/bin/hugo
      strip --remove-section=.comment --remove-section=.note $SNAPCRAFT_PART_INSTALL/bin/hugo
      ls -l $SNAPCRAFT_PART_INSTALL/bin/hugo
    after: [go]

  go:
    source-tag: go1.11

  git:
    plugin: nil
    stage-packages: [git]
    prime: [usr/bin/git]


apps:
  hugo:
    command: hugo server -s $SNAP --bind 0.0.0.0 --disableLiveReload 
    daemon: simple
    plugs: [network, network-bind]

