name: demo-hugo-site
version: 0.1
summary: Demo Hugo Site - Snap a hugo site
description: |
 Build a hugo site and snap it with a webserver.

grade: stable
confinement: strict

parts:
  content:
    plugin: dump
    stage: [config.toml,archetypes, content, data, layouts, static, themes]

  webserver:
    source: https://github.com/gohugoio/hugo.git
    source-type: git
    plugin: go
    go-importpath: github.com/gohugoio/hugo


apps:
  webserver:
    command: hugo server -s $SNAP
    daemon: simple
    plugs: [network, network-bind]

