name: demo-hugo-site
version: 0.1
summary: Demo Hugo Site - Snap a hugo site
description: |
 Build a hugo site and snap it with a webserver.

grade: stable
confinement: strict
environment:
    GO111MODULE: 'on'

parts:
  content:
    plugin: dump
    stage: [config.toml,archetypes, content, data, layouts, static, themes]
    after: [hugo]

  hugo:
    plugin: nil
    override-build: |
      echo "\nStarting override-build:"
      url=""
      case "$SNAP_ARCH" in
      amd64) 
      url=https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_0.48_Linux-64bit.tar.gz
      ;;
      armf)
      url=https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_0.48_Linux-ARM.tar.gz
      ;;
      arm64)
      url=https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_0.48_Linux-ARM64.tar.gz
      ;;
      i368)
      url=https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_0.48_Linux-32bit.tar.gz
      ;;
      *)
      echo SNAP_ARCH unknow type $SNAP_ARCH
      env
      exit 1
      esac
      curl $url -L --output hugo.tar.gz
      tar -xvzf hugo.tar.gz
      install -d $SNAPCRAFT_PART_INSTALL/bin
      cp -av hugo $SNAPCRAFT_PART_INSTALL/bin/


apps:
  hugo:
    command: hugo server -s $SNAP --bind 0.0.0.0 --disableLiveReload 
    daemon: simple
    plugs: [network, network-bind]

